# Generated by Django 2.1.5 on 2019-02-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profiles_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='job',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='location',
            field=models.CharField(default='My default location ', max_length=30),
        ),
    ]
