# Generated by Django 2.1.5 on 2019-02-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20190204_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='job',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='location',
            field=models.CharField(blank='True', default='My default location', max_length=30),
        ),
    ]
