# Generated by Django 2.1.5 on 2019-02-05 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20190204_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='job',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='location',
        ),
    ]
