# Generated by Django 2.1.5 on 2019-02-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20190205_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
